(ns gltut.gl12
  (:use [gltut.importer]))

(import-method org.lwjgl.opengl.GL12 glDrawRangeElements gl-draw-range-elements)
(import-method org.lwjgl.opengl.GL12 glDrawRangeElements gl-draw-range-elements)
(import-method org.lwjgl.opengl.GL12 glDrawRangeElements gl-draw-range-elements)
(import-method org.lwjgl.opengl.GL12 glDrawRangeElements gl-draw-range-elements)
(import-method org.lwjgl.opengl.GL12 glTexImage3D gl-tex-image3d)
(import-method org.lwjgl.opengl.GL12 glTexImage3D gl-tex-image3d)
(import-method org.lwjgl.opengl.GL12 glTexImage3D gl-tex-image3d)
(import-method org.lwjgl.opengl.GL12 glTexImage3D gl-tex-image3d)
(import-method org.lwjgl.opengl.GL12 glTexImage3D gl-tex-image3d)
(import-method org.lwjgl.opengl.GL12 glTexImage3D gl-tex-image3d)
(import-method org.lwjgl.opengl.GL12 glTexSubImage3D gl-tex-sub-image3d)
(import-method org.lwjgl.opengl.GL12 glTexSubImage3D gl-tex-sub-image3d)
(import-method org.lwjgl.opengl.GL12 glTexSubImage3D gl-tex-sub-image3d)
(import-method org.lwjgl.opengl.GL12 glTexSubImage3D gl-tex-sub-image3d)
(import-method org.lwjgl.opengl.GL12 glTexSubImage3D gl-tex-sub-image3d)
(import-method org.lwjgl.opengl.GL12 glTexSubImage3D gl-tex-sub-image3d)
(import-method org.lwjgl.opengl.GL12 glCopyTexSubImage3D gl-copy-tex-sub-image3d)

