(ns gltut.gl13
  (:use [gltut.importer]))

(import-method org.lwjgl.opengl.GL13 glClientActiveTexture gl-client-active-texture)
(import-method org.lwjgl.opengl.GL13 glActiveTexture gl-active-texture)
(import-method org.lwjgl.opengl.GL13 glCompressedTexImage1D gl-compressed-tex-image1d)
(import-method org.lwjgl.opengl.GL13 glCompressedTexImage1D gl-compressed-tex-image1d)
(import-method org.lwjgl.opengl.GL13 glCompressedTexImage2D gl-compressed-tex-image2d)
(import-method org.lwjgl.opengl.GL13 glCompressedTexImage2D gl-compressed-tex-image2d)
(import-method org.lwjgl.opengl.GL13 glCompressedTexImage3D gl-compressed-tex-image3d)
(import-method org.lwjgl.opengl.GL13 glCompressedTexImage3D gl-compressed-tex-image3d)
(import-method org.lwjgl.opengl.GL13 glCompressedTexSubImage1D gl-compressed-tex-sub-image1d)
(import-method org.lwjgl.opengl.GL13 glCompressedTexSubImage1D gl-compressed-tex-sub-image1d)
(import-method org.lwjgl.opengl.GL13 glCompressedTexSubImage2D gl-compressed-tex-sub-image2d)
(import-method org.lwjgl.opengl.GL13 glCompressedTexSubImage2D gl-compressed-tex-sub-image2d)
(import-method org.lwjgl.opengl.GL13 glCompressedTexSubImage3D gl-compressed-tex-sub-image3d)
(import-method org.lwjgl.opengl.GL13 glCompressedTexSubImage3D gl-compressed-tex-sub-image3d)
(import-method org.lwjgl.opengl.GL13 glGetCompressedTexImage gl-get-compressed-tex-image)
(import-method org.lwjgl.opengl.GL13 glGetCompressedTexImage gl-get-compressed-tex-image)
(import-method org.lwjgl.opengl.GL13 glGetCompressedTexImage gl-get-compressed-tex-image)
(import-method org.lwjgl.opengl.GL13 glGetCompressedTexImage gl-get-compressed-tex-image)
(import-method org.lwjgl.opengl.GL13 glMultiTexCoord1f gl-multi-tex-coord1f)
(import-method org.lwjgl.opengl.GL13 glMultiTexCoord1d gl-multi-tex-coord1d)
(import-method org.lwjgl.opengl.GL13 glMultiTexCoord2f gl-multi-tex-coord2f)
(import-method org.lwjgl.opengl.GL13 glMultiTexCoord2d gl-multi-tex-coord2d)
(import-method org.lwjgl.opengl.GL13 glMultiTexCoord3f gl-multi-tex-coord3f)
(import-method org.lwjgl.opengl.GL13 glMultiTexCoord3d gl-multi-tex-coord3d)
(import-method org.lwjgl.opengl.GL13 glMultiTexCoord4f gl-multi-tex-coord4f)
(import-method org.lwjgl.opengl.GL13 glMultiTexCoord4d gl-multi-tex-coord4d)
(import-method org.lwjgl.opengl.GL13 glLoadTransposeMatrix gl-load-transpose-matrix)
(import-method org.lwjgl.opengl.GL13 glLoadTransposeMatrix gl-load-transpose-matrix)
(import-method org.lwjgl.opengl.GL13 glMultTransposeMatrix gl-mult-transpose-matrix)
(import-method org.lwjgl.opengl.GL13 glMultTransposeMatrix gl-mult-transpose-matrix)
(import-method org.lwjgl.opengl.GL13 glSampleCoverage gl-sample-coverage)
